### ISSUE TITLE
Understanding need for POST requests

### ISSUE THREAD

**Issue by istathar** [commercialhaskell/casa#13]
Hey everyone. Can you explain why **casa** needs to make POST requests to talk to the server?

We need to talk through restricted proxy caches from our build servers, and upgrading to stack 2.3.1 has proven problematic.  We've gone and set up a mirror of https://casa.fpcomplete.com/ and are using `casa-repo-prefix: https://internal-mirror.example.com/com.fpcomplete.casa/` in _~/.stack/config.yaml_ but it's only able to pass through (and cache) HEAD and GET requests (we get 405 Method Not Allowed back from the proxy cache server).

Have you any workaround to suggest? As we understand it the point of CASA was to be immutable content addressable storage which we hope will work great with corporate proxies caches in contexts where unrestricted internet access is unavailable. Please do let us know if you have any suggestions.

**Comment by snoyberg** [comment]
Instead of making a separate HTTP request for each blob, we batch a large number of requests together by creating an HTTP request body with a number of blob IDs. This requires using an HTTP method that reliably supports request bodies.

In theory, someone could add a setting to turn off this batching. Or you could set up a full Casa mirror internally.

**Comment by istathar** [comment]
Hey @snoyberg thanks for your reply. By mirror you mean "run a casa server locally"? ... but that server would still need access to the upstream CASA, right? Could it communicate to that upstream in a read-only (HTTP caching no POSTing) fashion? (servers on the network here don't get unrestricted internet access)

**Comment by snoyberg** [comment]
I don't think it's configured that way right now, I was thinking about running your own Casa server and manually loading up the data you need. It's certainly possible to extend both Casa server and client to meet this kind of use case, but it would require changes to the codebase. It does currently assume that it's possible to make a POST request.

**Comment by istathar** [comment]
Is there a way to know what "the data you need" is? There's little to zero logging from the casa layer in **stack**'s debug output so we're a bit in the dark about what it's doing. Failing that, is use of CASA something we can turn off in stack 2.3.1?

Sorry to bug you with all this. I know why you built CASA, and I think it's a great idea. Just thought **stack** was going to be a bit more corporate-HTTP-cache-behind-the-firewall friendly as a result of all this. If hacking **casa-client** to not use POST requests is the answer, then we can embark on that for you. Hopefully we can figure out a workaround in the mean time. Cheers!

**Comment by snoyberg** [comment]
You may want to try the latest Stack master, which may address this by making Casa failures non fatal. In my opinion, best option is really too get a full Casa server running inside your firewall.

**Comment by istathar** [comment]
> You may want to try the latest Stack master,

Gave it a run with today's stack from `'master'` and indeed builds complete when simulating the lack of internet access that our CI/CD environment has. I get the impression it's waiting for the HTTP connection to timeout before erroring, which is a shame but in CI is hardly a show-stopper. (It also seemed to get faster so do you cache that response? `--verbose` is a lot to read) Anyway, yes, that was a workaround for now. Most kind.

There's a lot more we could ask about Casa and its expected behaviour but we'll leave that for elsewhere.

**Comment by istathar** [comment]
P.S. A `stack-2.3.2` release tarball would be most welcome if you think others might also benefit from this.
