### ISSUE TITLE
Make a new release for the patch?

### ISSUE THREAD

**Issue by chenrui333** [commercialhaskell/casa#15]
👋 Right now it seems haskell-stack 2.5.1 is broken due to base16-bytestring-1.0.0.0 compatibility. 

Given that you have merged a fix (#14), I wonder if you can make a release to hackage index? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/62939

cc @chrisdone

**Comment by chreekat** [comment]
Looks like #14 exists in version 0.0.2, so I'll close this!
