### ISSUE TITLE
sqlite driver locks up on /v1/pull

### ISSUE THREAD

**Issue by dpwiz** [commercialhaskell/casa#16]
> 10.0.0.123 - - [23/Oct/2020:01:16:13 +0000] "POST /v1/pull HTTP/1.1" 500 213 "" ""

> 23/Oct/2020:01:16:13 +0000 [Error#yesod-core] SQLite3 returned ErrorBusy while attempting to perform step: database is locked @(yesod-core-1.6.14-8xhOMyjO2WXI2BIxH2nqnt:Yesod.Core.Class.Yesod src/Yesod/Core/Class/Yesod.hs:676:5)

Moving to PostgreSQL is an option of course, but keeping things contained in sqlite would be nice.

**Comment by chrisdone** [comment]
If you use sqlite in a concurrent setting, you'll have to configure the pool size to be `1`.

**Comment by dpwiz** [comment]
Um.. Yes, but the pool size looks [hardcoded](https://github.com/fpco/casa/blob/3dee7dc1594e4d0ea2b101ad933ce23b4bc3c451/casa-server/src/Casa/Server.hs#L430) to 10.

It isn't possible to override it with DBCON env, is it?
