### ISSUE TITLE
Use `crypton` instead of `cryptonite`

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/casa#18]
See https://github.com/yesodweb/wai/pull/931 and https://github.com/kazu-yamamoto/crypton/issues/5#issuecomment-1587161844 and the corresponding Stack issue https://github.com/commercialhaskell/stack/issues/6200.

**Comment by mpilgrem** [comment]
@snoyberg, many thanks. Can this be released? I see that @chrisdone is the only Maintainer of `casa-client` on Hackage.

**Comment by snoyberg** [comment]
Thanks to @chrisdone for sharing maintainer perms. I've uploaded a new version of casa-client, plus granted maintainer perms to @mpilgrem as well.
